# 1. Utiliser une image Python officielle légère
FROM python:3.12-slim

# 2. Définir le dossier de travail dans le conteneur
WORKDIR /app

# 3. Copier les dépendances et les installer
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copier tout ton code dans le conteneur
COPY . .

# 5. Commande exécutée au démarrage du conteneur
CMD ["python", "scheduled-duration-prediction.py"]